name: test_app_5843980
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.4.3+1
  intl: ^0.19.0
  async: ^2.11.0
  google_fonts: 6.0.0
  flutter_bloc: ^8.1.5
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  freezed: ^2.5.2
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
